name: sm_parser
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - ahocorasick_rs==0.9.1
      - aniso8601==9.0.1
      - attrs==21.2.0
      - cachelib==0.2.0
      - certifi==2021.5.30
      - cffi==1.14.6
      - chardet==4.0.0
      - charset-normalizer==2.0.3
      - click==8.0.1
      - colorama==0.4.4
      - fastobo==0.10.2
      - flask==2.0.1
      - flask-cors==3.0.10
      - flask-jwt-extended==4.4.1
      - flask-restplus==0.13.0
      - flask-session==0.4.0
      - flask-wtf==0.15.1
      - gevent==21.1.2
      - greenlet==1.1.0
      - idna==3.2
      - itsdangerous==2.0.1
      - jinja2==3.0.1
      - joblib==1.1.0
      - jsonschema==3.2.0
      - markupsafe==2.0.1
      - networkx==2.6.2
      - nltk==3.6.2
      - numpy==1.21.0
      - pandas==1.3.0
      - pronto==2.4.3
      - pycparser==2.20
      - pyjwt==2.4.0
      - pyrsistent==0.18.0
      - python-dateutil==2.8.1
      - python-dotenv==0.18.0
      - pytz==2021.1
      - regex==2021.11.10
      - requests==2.26.0
      - setuptools==58.1.0
      - six==1.16.0
      - tqdm==4.62.3
      - urllib3==1.26.6
      - werkzeug==2.0.1
      - wtforms==2.3.3
      - zope.event==4.5.0
      - zope.interface==5.4.0
